In [ ]:
1.#identify the problem statement 
#TAKE AWAY
#to predict the insurance charges is output  remain are input its ML(number)
#i/p and output clear--its supervising Learning
#words-convert to (0,1,2,3)/(0,1,0  1,0,0  0,0,1 ) classification --no decimal -discrete
#one output =insurance purchase(yes/no) and remain multiple inputs

1.0

1.0

In [1]:
#import libraries
import pandas as pd
import numpy as np

In [2]:
data=pd.read_csv("Social_Network_Ads.csv")

In [3]:
data

User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [111]:
data=data.drop("User ID",axis=1)

In [5]:
data.columns

Index(['User ID', 'Gender', 'Age', 'EstimatedSalary', 'Purchased'], dtype='object')

In [7]:
data["Purchased"].value_counts()

Purchased
0    257
1    143
Name: count, dtype: int64

In [11]:
data=pd.get_dummies(data,drop_first=True)

In [12]:
data=data.astype(int)
#2024 update to show 0 and 1

In [13]:
data

User ID  Age  EstimatedSalary  Purchased  Gender_Male
0    15624510   19            19000          0            1
1    15810944   35            20000          0            1
2    15668575   26            43000          0            0
3    15603246   27            57000          0            0
4    15804002   19            76000          0            1
..        ...  ...              ...        ...          ...
395  15691863   46            41000          1            0
396  15706071   51            23000          1            1
397  15654296   50            20000          1            0
398  15755018   36            33000          0            1
399  15594041   49            36000          1            0

[400 rows x 5 columns]

In [ ]:
4#Develop a good model with accuracy.

4

4

In [ ]:
#use any machine learning algorithm; you can create many models. Finally, you have to come up with best accuracy as final model.

In [14]:
data.columns

Index(['User ID', 'Age', 'EstimatedSalary', 'Purchased', 'Gender_Male'], dtype='object')

In [15]:
#multiple inputs
indep=data[['Age', 'EstimatedSalary', 'Gender_Male']]
#one output
dep=data[['Purchased']]

In [16]:
#model feature selection
from sklearn.model_selection import train_test_split
#tran 70,test 30 same order below
X_train,X_test,y_train,y_test=train_test_split(indep,dep,test_size=0.30,random_state=0)
#errors  X_train not defined  check spelling full code/== remove 
#restart kernel if required


# Logistic Regrission  is to do the work of classifiaction

In [27]:
#LR  model creation
from sklearn.linear_model import LogisticRegression
mlcls=LogisticRegression(penalty='l2',  C=1.0, fit_intercept=True, intercept_scaling=1,  random_state=None, solver='liblinear', max_iter=6, multi_class='ovr', verbose=3, warm_start=False, n_jobs=2)
mlcls.fit(X_train,y_train)
#ValueError: Only 'saga' solver supports elasticnet penalty, got solver=liblinear.
#InvalidParameterError: The 'C' parameter of LogisticRegression must be a float in the range (0.0, inf]. Got 'float' instead.

[LibLinear]

C:\Users\hp\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\hp\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:1222: UserWarning: 'n_jobs' > 1 does not have any effect when 'solver' is set to 'liblinear'. Got 'n_jobs' = 2.
  warnings.warn(
C:\Users\hp\anaconda3\Lib\site-packages\sklearn\svm\_base.py:1242: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(


LogisticRegression(max_iter=6, multi_class='ovr', n_jobs=2, solver='liblinear',
                   verbose=3)

In [ ]:
# Viewing the b1,b2 are weights and bo is bias 
#checking weight and bias 
#weight=regressor.coef_
#print("Weight of the model={}".format(weight))
#bais=regressor.intercept_
#print("Intercept of the model={}".format(bais))

In [28]:
y_pred_mlc=mlcls.predict(X_test)
#y_pred predected output

In [29]:
#evaluation metric
from sklearn.metrics import confusion_matrix
lc_cm=confusion_matrix(y_test,y_pred_mlc)

In [24]:
lc_cm

array([[79,  0],
       [41,  0]], dtype=int64)

In [33]:
from sklearn.metrics import classification_report
lc_cr=classification_report(y_test,y_pred_mlc)
print(lc_cr)

              precision    recall  f1-score   support

           0       0.66      1.00      0.79        79
           1       0.00      0.00      0.00        41

    accuracy                           0.66       120
   macro avg       0.33      0.50      0.40       120
weighted avg       0.43      0.66      0.52       120



C:\Users\hp\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\hp\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\hp\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


# SVM : Super Vector Machine
#SVC -classification

In [36]:
#model creation
from sklearn.svm import SVC
svc_cls=SVC(kernel="linear",C=0.1)
#hyper parameter =C, r value=linear.nonlinear(rbf),poly,sigmoid
svc_cls.fit(X_train,y_train)

C:\Users\hp\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(C=0.1, kernel='linear')

In [37]:
y_pred_svc=svc_cls.predict(X_test)
#y_pred predected output

In [38]:
#evaluation metric
from sklearn.metrics import confusion_matrix
svc_cm=confusion_matrix(y_test,y_pred_svc)

In [39]:
print(svc_cm)
#svc accuracy print

[[72  7]
 [ 9 32]]


In [41]:
from sklearn.metrics import classification_report
svc_cr=classification_report(y_test,y_pred_svc)

In [42]:
print(svc_cr)

              precision    recall  f1-score   support

           0       0.89      0.91      0.90        79
           1       0.82      0.78      0.80        41

    accuracy                           0.87       120
   macro avg       0.85      0.85      0.85       120
weighted avg       0.87      0.87      0.87       120



In [ ]:
#below scalar not given good accuracy

In [43]:
# Scale features for models sensitive to scaling (SVR, optional for others)
#standarisation
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [44]:
ypred_svc_sc=svc_cls.predict(X_test_scaled)
#y_pred predected output

C:\Users\hp\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(


In [48]:
#evaluation metric
from sklearn.metrics import confusion_matrix
cm_sv_sc=confusion_matrix(y_test,ypred_svc_sc)

In [49]:
print(cm_sv_sc)
#svr accuracy

[[79  0]
 [41  0]]


In [51]:
from sklearn.metrics import classification_report
svc_cr_sc=classification_report(y_test,ypred_svc_sc)

C:\Users\hp\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\hp\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\hp\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [52]:
print(svc_cr_sc)

              precision    recall  f1-score   support

           0       0.66      1.00      0.79        79
           1       0.00      0.00      0.00        41

    accuracy                           0.66       120
   macro avg       0.33      0.50      0.40       120
weighted avg       0.43      0.66      0.52       120



# DecisionTree

In [55]:
#model creation 
from sklearn.tree import DecisionTreeClassifier
dt_cls=DecisionTreeClassifier(criterion='log_loss', splitter='best',max_features=None)
dt_clsr=dt_cls.fit(X_train,y_train)

In [56]:
y_pred_dt=dt_cls.predict(X_test)
#y_pred predected output

In [59]:
#evaluation metric
from sklearn.metrics import confusion_matrix
dt_cm=confusion_matrix(y_test,y_pred_dt)

In [60]:
dt_cm
#decision tree Confusion Matrics (accuracy)

array([[71,  8],
       [ 4, 37]], dtype=int64)

In [61]:
from sklearn.metrics import classification_report
dt_cr=classification_report(y_test,y_pred_dt)
print(dt_cr)

              precision    recall  f1-score   support

           0       0.95      0.90      0.92        79
           1       0.82      0.90      0.86        41

    accuracy                           0.90       120
   macro avg       0.88      0.90      0.89       120
weighted avg       0.90      0.90      0.90       120



# Random Forest

In [62]:
#import RF model algarithm
from sklearn.ensemble import RandomForestClassifier
rf_cls = RandomForestClassifier(n_estimators = 50, random_state = 0)  #  n_estimators less number decresed accuracy    
rf_cls.fit(X_train, y_train)
#model creation

C:\Users\hp\anaconda3\Lib\site-packages\sklearn\base.py:1151: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)


RandomForestClassifier(n_estimators=50, random_state=0)

In [63]:
y_pred_rf=rf_cls.predict(X_test)
#y_ore predicted score

In [65]:
#evaluation metric
from sklearn.metrics import confusion_matrix
cm_rf=confusion_matrix(y_test,y_pred_rf)

In [66]:
print(cm_rf)
#random forest accuracy

[[73  6]
 [ 5 36]]


In [67]:
from sklearn.metrics import classification_report
cm_cr=classification_report(y_test,y_pred_rf)
print(cm_cr)

              precision    recall  f1-score   support

           0       0.94      0.92      0.93        79
           1       0.86      0.88      0.87        41

    accuracy                           0.91       120
   macro avg       0.90      0.90      0.90       120
weighted avg       0.91      0.91      0.91       120



# Kneighborsclassifier

In [74]:
#import KNN model algarithm
from sklearn.neighbors import KNeighborsClassifier
knn_cls = KNeighborsClassifier(n_neighbors=3)  #  n_estimators less number decresed accuracy    
knn_cls.fit(X_train, y_train)
#model creation

C:\Users\hp\anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py:228: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier(n_neighbors=3)

In [75]:
y_pred_knn=knn_cls.predict(X_test)
#y_ore predicted score

In [76]:
#evaluation metric
from sklearn.metrics import confusion_matrix
cm_knn=confusion_matrix(y_test,y_pred_knn)
cm_knn

array([[65, 14],
       [14, 27]], dtype=int64)

In [77]:
from sklearn.metrics import classification_report
cr_knn=classification_report(y_test,y_pred_knn)
print(cr_knn)

              precision    recall  f1-score   support

           0       0.82      0.82      0.82        79
           1       0.66      0.66      0.66        41

    accuracy                           0.77       120
   macro avg       0.74      0.74      0.74       120
weighted avg       0.77      0.77      0.77       120



# NavieBayes  GaussianNB

In [80]:
#import KNN model algarithm
from sklearn.naive_bayes import GaussianNB
nv_cls = GaussianNB(priors=None, var_smoothing=1e-09)  #  n_estimators less number decresed accuracy    
nv_cls.fit(X_train, y_train)
#model creation

C:\Users\hp\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


GaussianNB()

In [81]:
y_pred_nv=nv_cls.predict(X_test)
#y_ore predicted score

In [82]:
#evaluation metric
from sklearn.metrics import confusion_matrix
cm_nv=confusion_matrix(y_test,y_pred_nv)
cm_nv

array([[74,  5],
       [ 8, 33]], dtype=int64)

In [83]:
from sklearn.metrics import classification_report
cr_nv=classification_report(y_test,y_pred_nv)
print(cr_nv)

              precision    recall  f1-score   support

           0       0.90      0.94      0.92        79
           1       0.87      0.80      0.84        41

    accuracy                           0.89       120
   macro avg       0.89      0.87      0.88       120
weighted avg       0.89      0.89      0.89       120



# Boosting Algorithm -Classificatio
# 1.Adaboost Classification

In [84]:
from sklearn.ensemble import AdaBoostClassifier
cls_ada = AdaBoostClassifier(random_state=0, n_estimators=100)
cls_ada.fit(X_train, y_train)

C:\Users\hp\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


AdaBoostClassifier(n_estimators=100, random_state=0)

In [86]:
y_pred_ada=cls_ada.predict(X_test)

In [87]:
#evaluation metric
from sklearn.metrics import confusion_matrix
cm_ada=confusion_matrix(y_test,y_pred_ada)

In [88]:
print(cm_ada)
#random forest accuracy

[[73  6]
 [ 8 33]]


In [89]:
from sklearn.metrics import classification_report
ada_cr=classification_report(y_test,y_pred_ada)
print(ada_cr)

              precision    recall  f1-score   support

           0       0.90      0.92      0.91        79
           1       0.85      0.80      0.83        41

    accuracy                           0.88       120
   macro avg       0.87      0.86      0.87       120
weighted avg       0.88      0.88      0.88       120



# 2.XG /Gradiant Boosting- Classification

In [95]:
from sklearn.ensemble import GradientBoostingClassifier
#from document ignore x,y and x_train take only from and reg,fit
cls_gb = GradientBoostingClassifier(random_state=0)
cls_gb.fit(X_train, y_train)

C:\Users\hp\anaconda3\Lib\site-packages\sklearn\ensemble\_gb.py:424: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


GradientBoostingClassifier(random_state=0)

In [97]:
y_pred_gb=cls_gb.predict(X_test)

In [98]:
#evaluation metric
from sklearn.metrics import confusion_matrix
cm_gb=confusion_matrix(y_test,y_pred_gb)
print(cm_gb)
#ValueError: Classification metrics can't handle a mix of binary and continuous targets   to fix,run y_pred_gb

[[75  4]
 [ 5 36]]


In [100]:
from sklearn.metrics import classification_report
gb_cr=classification_report(y_test,y_pred_gb)
print(gb_cr)

              precision    recall  f1-score   support

           0       0.94      0.95      0.94        79
           1       0.90      0.88      0.89        41

    accuracy                           0.93       120
   macro avg       0.92      0.91      0.92       120
weighted avg       0.92      0.93      0.92       120



# 3.LG Boosting

In [152]:
!pip install lightgbm

  Obtaining dependency information for lightgbm from https://files.pythonhosted.org/packages/d9/28/3be76b591a2e14a031b681b8283acf1dec2ad521f6f1701b7957df68c466/lightgbm-4.5.0-py3-none-win_amd64.whl.metadata
   ---------------------------------------- 0.0/1.4 MB ? eta -:--:--
   ----- ---------------------------------- 0.2/1.4 MB 6.1 MB/s eta 0:00:01
   ------------- -------------------------- 0.5/1.4 MB 6.0 MB/s eta 0:00:01
   ---------------------- ----------------- 0.8/1.4 MB 6.3 MB/s eta 0:00:01
   ------------------------------ --------- 1.1/1.4 MB 6.3 MB/s eta 0:00:01
   ---------------------------------------  1.4/1.4 MB 6.5 MB/s eta 0:00:01
   ---------------------------------------- 1.4/1.4 MB 5.7 MB/s eta 0:00:00


In [101]:
import lightgbm as lgb 

In [102]:
#from sklearn.preprocessing import StandardScaler 
#from sklearn.model_selection import train_test_split 
import warnings 
warnings.filterwarnings('ignore')
#from sklearn.metrics import mean_squared_error as mse 
from lightgbm import LGBMClassifier
  
# Create an instance of the LightGBM Regressor with the RMSE metric. 
cls_lgb = LGBMClassifier(metric='rmse') 
  
# Train the model using the training data. 
cls_lgb.fit(X_train, y_train) 

[LightGBM] [Info] Number of positive: 102, number of negative: 178
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001552 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 106
[LightGBM] [Info] Number of data points in the train set: 280, number of used features: 3
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.364286 -> initscore=-0.556811
[LightGBM] [Info] Start training from score -0.556811
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf


LGBMClassifier(metric='rmse')

In [103]:
y_pred_lgb=cls_lgb.predict(X_test)

In [104]:
#evaluation metric
from sklearn.metrics import confusion_matrix
cm_lgb=confusion_matrix(y_test,y_pred_lgb)
cm_lgb

array([[75,  4],
       [ 7, 34]], dtype=int64)

In [105]:
from sklearn.metrics import classification_report
lgb_cr=classification_report(y_test,y_pred_lgb)
print(lgb_cr)

              precision    recall  f1-score   support

           0       0.91      0.95      0.93        79
           1       0.89      0.83      0.86        41

    accuracy                           0.91       120
   macro avg       0.90      0.89      0.90       120
weighted avg       0.91      0.91      0.91       120



In [ ]:

#from sklearn.metrics import accuracy_score, f1_score
#accuracy = accuracy_score(y_test, y_pred_gb)
#f1 = f1_score(y_test, y_pred_gb, average='weighted')


In [107]:
#save best model
import pickle
filename="best_classification_model_gb.sav"
pickle.dump(reg_gb,open(filename,'wb'))
#reg_gb is regressor

In [108]:
#load model
loaded_model=pickle.load(open("best_classification_model_gb.sav",'rb'))


In [112]:
data.columns

Index(['Age', 'EstimatedSalary', 'Purchased', 'Gender_Male'], dtype='object')

In [110]:
loaded_model.predict

<bound method GradientBoostingRegressor.predict of GradientBoostingRegressor(random_state=0)>

In [113]:
# get target using multi fixed inputs 
result=loaded_model.predict([[36,15000,1]])
#[][] to fix value error
print("Purchased",result)

Purchased [0.04530715]


In [114]:
# get target using dynamic fixed inputs
#input pass dynamically
age_input=float(input("Age:"))
sal_input=float(input("EstimatedSalary"))
male_yes_input=int(input("Gender_Male 0 or 1:"))

Age:35
EstimatedSalary23300
Gender_Male 0 or 1:1


In [115]:
result=loaded_model.predict([[age_input,sal_input,male_yes_input]])
print("Total Charges are= ",result)

Total Charges are=  [0.01622513]
